matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "10"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint

    - stage: "Build and Test"
      env:
        - BuildAndroid="29"
        - NodeJs="8"
        - Type="TypeScript"
      language: android
      dist: trusty
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8
      script: cd demo && npm run build.plugin && npm i && tns build android --env.uglify --env.snapshot

    - env:
        - BuildAndroid="29"
        - Type="TypeScript"
      language: android
      dist: trusty
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 10
      script: cd demo && npm run build.plugin && npm i && tns build android --env.uglify --env.snapshot

    - os: osx
      env:
        - BuildiOS="12.0"
        - Type="TypeScript"
      osx_image: xcode11.2
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      script: cd demo && npm run build.plugin && npm i && tns build ios --env.uglify

    - os: linux
      language: android
      dist: trusty
      sudo: required
      env:
        - UnitTest="Android"
        - TestVersion="latest"
      jdk: oraclejdk8
      before_install:
        - nvm install 10
      before_script:
        - android list targets
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      script: cd src && travis_wait travis_retry npm run test.android
    - os: osx
      env:
        - UnitTest="iOS"
        - TestVersion="latest"
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      osx_image: xcode11.2
      script: cd src && npm run test.ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-21
    - android-29
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:
    - sudo pip install --upgrade pip
    - sudo pip install six

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
